# Generated by Django 4.2.11 on 2024-11-20 08:01

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("video_file_upload", models.URLField(blank=True, null=True)),
                ("video_file_transcoded", models.URLField(blank=True, null=True)),
                (
                    "share_link",
                    models.CharField(
                        blank=True, max_length=225, null=True, unique=True
                    ),
                ),
                ("link_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("watermark", models.BooleanField(default=False)),
                (
                    "watermark_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top_left", "Top Left"),
                            ("top_right", "Top Right"),
                            ("bottom_left", "Bottom Left"),
                            ("bottom_right", "Bottom Right"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("watermark_start_time", models.DurationField(blank=True, null=True)),
                ("watermark_end_time", models.DurationField(blank=True, null=True)),
                ("watermark_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "total_view_duration",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "average_view_duration",
                    models.DurationField(blank=True, default=None, null=True),
                ),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("bounce_rate", models.FloatField(default=0.0)),
                ("video_length", models.DurationField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("view_date", models.DateField(auto_now_add=True, null=True)),
                ("unique_view_count", models.PositiveIntegerField(default=0)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_date", models.DateField()),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("video", "view_date")},
            },
        ),
        migrations.CreateModel(
            name="UniqueVideoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("view_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unique_views",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("video", "user", "unique_identifier", "view_date")
                },
            },
        ),
    ]
