# Generated by Django 4.2.11 on 2024-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription_subscription_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
