# Generated by Django 4.2.11 on 2024-12-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_subscription_stripe_checkout_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="transaction_status",
            field=models.CharField(
                blank=True,
                choices=[("success", "Success"), ("cancelled", "Cancelled")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_tier",
            field=models.CharField(
                blank=True,
                choices=[("standard", "Standard"), ("advanced", "Advanced")],
                max_length=20,
                null=True,
            ),
        ),
    ]
